name: Makefile CI

on:
  push:
    branches: ["branchAutomake"]
  pull_request:
    branches: ["branchAutomake"]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: chekout_code
        uses: actions/checkout@v2

      - name: dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake make g++
      - name: config
        run: |
          aclocal
          autoconf
          automake --add-missing
      - name: build-configure
        run: |
          ./configure
          make
          make check
      - name: Create tarball distribution
        run: make dist

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: program-tarball
          path: program-*.tar.gz